// Do not edit. This file is machine generated by the Resource DLL Wizard.

library Project1;

{ITE} {DFMFileType} {Login.dfm}
{ITE} {DFMFileType} {MainForm.dfm}
{ITE} {DFMFileType} {Register.dfm}
{ITE} {DFMFileType} {Search123.dfm}
{ITE} {DFMFileType} {Settings.dfm}
{ITE} {RCFileType} {Project1_DRC.rc}

{$R 'Login.dfm' 'FormLogin:TForm'}
{$R 'MainForm.dfm' 'FormHome:TForm'}
{$R 'Register.dfm' 'FormRegister:TForm'}
{$R 'Search123.dfm' 'FormSearch:TForm'}
{$R 'Settings.dfm' 'FormSettings:TForm'}
{$R 'Project1_DRC.res' 'Project1_DRC.rc'}

{$E ENG}

begin
end.
